name: Timba CD

on:
  push:
    #branches:
    #  - master

jobs:
  publish-web:
    name: Publish web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v1
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Run peanut
        run: |
          flutter pub global activate peanut
          flutter pub global run peanut:peanut
      - name: Push changes to origin/gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'