name: Timba CD - Publish Web

on:
  push:
    branches:
      - master

jobs:
  publish-web:
    name: Publish web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Enable Flutter web
        run: flutter config --enable-web
      - name: Get packages
        run: flutter pub get
      - name: Build runner
        run: flutter pub run build_runner build
      - name: Build
        run: flutter build web --release
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
