name: Flutter CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v1
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Get packages
        run: flutter pub get
      - name: Run unit tests
        run: flutter test
  end-to-end-web:
    name: End to end tests (Web)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v1
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Enable web for Flutter
        run: flutter config --enable-web
      - name: Clone web installers
        uses: actions/checkout@master
        with:
          name: flutter/web_installers
      - name: Go to web drivers folder
        run: cd web_installers/packages/web_drivers/
      - name: Get web drivers packages
        run: pub get
      - name: Install web driver
        run: dart lib/web_driver_installer.dart &
      - name: Wait for completion
        run: sleep 20
      - name: run Chrome driver
        run: chromedriver/chromedriver --port=4444 &
      - name: Wait Chrome driver for initialization
        run: sleep 5
      - name: Go back to the project
        run: cd ../../../
      - name: Get packages
        run: flutter pub get
      - name: Run web flutter driver tests
        run: flutter drive --target=test_driver/app.dart -d web-server --release --browser-name=chrome --web-port=8080
  end-to-end-Android:
    name: End to end tests (Android)
    runs-on: macOS-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Get packages
        run: flutter pub get
      - name: Run Android Emulator and Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: flutter drive --target=test_driver/app.dart
  end-to-end-iOS:
    name: End to end tests (iOS)
    strategy:
      matrix:
        device:
          - iPhone 8 (13.4.1)
      fail-fast: false
    runs-on: macOS-latest
    steps:
      - name: List all simulators
        run: xcrun instruments -s
      - name: Start Simulator
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=${{ matrix.device }}' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - name: Checkout the branch
        uses: actions/checkout@v1
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Get packages
        run: flutter pub get
      - name: Run Flutter Driver tests
        run: flutter drive --target=test_driver/app.dart