name: Timba CI - End to end Android

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  end-to-end-Android:
    name: End to end tests (Android)
    runs-on: macOS-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Get packages
        run: flutter pub get
      - name: Build runner
        run: flutter pub run build_runner build
      - name: Build APK
        run: flutter build apk
      - name: Run Android Emulator and Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: flutter drive --target=test_driver/app.dart