name: Timba CI - Unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v1
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Get packages
        run: flutter pub get
      - name: Run unit tests
        run: flutter test